DROP TABLE IF EXISTS NELIST;
CREATE TABLE NELIST(
	NODE_DESCRIPTION TEXT
	,NODE_IP TEXT
	,NODE_MGMT_IP TEXT
	,NODE_MODEL TEXT
	,NODE_NAME TEXT
	,NODE_SW TEXT
	,NODE_SERIAL TEXT
	,NODE_TYPE TEXT
	,NODE_VENDOR TEXT
	,VERSION TXT
);
